spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.0.1.15:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
#  context-path: /sell
  port: 8082
wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: f284e49e5c55ad31c442c7a14253c661
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: h5.p12
  notifyUrl: http://jimmmy.natapp1.cc/notify